### ISSUE TITLE
SyntaxError: Unexpected token # in JSON at position 0

### ISSUE THREAD

**Issue by parilyak** [matEhickey/atom-json-format#1]
The issue: 

When trying to ctrl+alt+j format the JSON content in the Atom editor, it throws an error "SyntaxError: Unexpected token # in JSON at position 0". 

The example of a JSON I was trying to convert in .md file (Perhaps, I am doing something wrong?): 
"{"Crows":{"players":{"Ben":{"position":"1B"},"Ty":{"position":"2B"}}},"Pigeons":{"players":{"Bill":{"position":"1B"},"Tim":{"position":"2B"}}},"Seagulls":{"players":{"Bob":{"position":"1B"},"Tom":{"position":"2B"}}}}"

How I tried to solve it:

1. Re-opened Atom, re-installed the package to make it work.

**Comment by matEhickey** [comment]
Hi !

Indeed, It's really weird,
at first I thought of a json syntax error, but your json is totally valid, and I can't even reproduce the error at home.  

In your editor, did you have:  
~~~
"{"Crows":{"players":{"Ben":{"position":"1B"},"Ty":{"position":"2B"}}},"Pigeons":{"players":{"Bill":{"position":"1B"},"Tim":{"position":"2B"}}},"Seagulls":{"players":{"Bob":{"position":"1B"},"Tom":{"position":"2B"}}}}"
~~~

or 

~~~
{"Crows":{"players":{"Ben":{"position":"1B"},"Ty":{"position":"2B"}}},"Pigeons":{"players":{"Bill":{"position":"1B"},"Tim":{"position":"2B"}}},"Seagulls":{"players":{"Bob":{"position":"1B"},"Tom":{"position":"2B"}}}}
~~~

(without the first opening and the last closing ") ?  

Only the second is a valid json string.

**Comment by parilyak** [comment]
Hello and thank you for your answer!

I had the second option. I re-installed your package and tried again with both options just to make sure, but unfortunately, it resulted in the same error. I also tried ctrl+alt+j and cmd+alt+j (the second one in case it's different for macOS) with no success. 
Please, let me know if I can take any other steps to help you reproduce or to give you more information. I like how how simple it should be to work with JSON using your package. 

![Screenshot 2021-03-30 at 9 48 38 PM](https://user-images.githubusercontent.com/38262254/113040634-b22d2f80-91a1-11eb-9475-50d90b27c823.png)

**Comment by matEhickey** [comment]
As you can see the error, I presume the shortcut is fonctionnal. 

I honestly dont yet understand what is hapenning.

Maybe a platform specific issue, i will test on a Mac tommorow (that's your platform, right ?).

For information, this package is very simple, it only take the content of the tab, parse it with Javascript JSON.parse, and send that to JSON.stringify to pretty format it.

Btw, thank you for reporting this issue ! 😊

**Comment by parilyak** [comment]
What you mean is that I have to create separate files for each json or I can just highlight what I need and press ctrl+alt+j? Perhaps, I am doing it the wrong way? 

And answering your question - yes, my platform is macOS (Big Sur 11.2.3)

**Comment by matEhickey** [comment]
That's it, actually you need the file to be only one (valid) json, so every json in differents files.
Actually, you dont need to save the file, so you can use a new tab to format parts of json.

It is a great idea to be able to format only selected text, I will try to think of a technical solution. I'll be happy to hear your suggestions if you have some !

**Comment by parilyak** [comment]
Hey, I've tried doing it with in a file and it works! Cool! Thank you so much for explaining! :) And yes formatting a selected part of the text where JSON is written would be a nice feature, hopefully we can see it implemented :) I am closing this issue now since everything works and I just misunderstood the steps.
