### ISSUE TITLE
Error SyntaxError: Unexpected token { in JSON at position 686

### ISSUE THREAD

**Issue by Dulanic** [matEhickey/atom-json-format#2]
I receive the following error. I can format it without issue in VSCode. I only compare to VS code to show it is not a issue with the json.

`SyntaxError: Unexpected token { in JSON at position 686`

Atom:
https://streamable.com/6j3iae
VSCode:
https://streamable.com/9rnnwf

Example of data:
```
{"level":"info","ts":1618970361.1968935,"logger":"http.log.access.log2","msg":"handled request","request":{"remote_addr":"162.158.123.22:14778","proto":"HTTP/1.1","method":"GET","host":"irc.dulanic.com","uri":"/audio/pop.wav","headers":{"User-Agent":["Mozilla/5.0 (Linux; Android 11; SM-G975U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/46.03.4.5155"],"Pragma":["no-cache"],"Cf-Connecting-Ip":["47.187.143.222"],"Cache-Control":["no-cache"],"Range":["bytes=0-"],"Cf-Ipcountry":["US"],"X-Forwarded-For":["47.187.143.222"]}},"common_log":"162.158.123.22 - - [21/Apr/2021:01:59:21 +0000] \"GET /audio/pop.wav HTTP/1.1\" 206 28366","status":206}
{"level":"info","ts":1618970361.2130616,"logger":"http.log.access.log2","msg":"handled request","request":{"remote_addr":"162.158.123.22:14780","proto":"HTTP/1.1","method":"GET","host":"sample.domain.com.dulanic.com","uri":"/socket.io/?EIO=3&transport=polling&t=NZo9pSv","headers":{"Cf-Connecting-Ip":["47.187.143.222"],"Cache-Control":["no-cache"],"Pragma":["no-cache"],"Cf-Ipcountry":["US"],"X-Forwarded-For":["47.187.143.222"],"User-Agent":["Mozilla/5.0 (Linux; Android 11; SM-G975U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/46.03.4.5155"]}},"common_log":"162.158.123.22 - - [21/Apr/2021:01:59:21 +0000] \"GET /socket.io/?EIO=3&transport=polling&t=NZo9pSv HTTP/1.1\" 200 92","status":200}

```

**Comment by matEhickey** [comment]
Hi,
The data you provided is not a valid json string, but concatenation of many with \n to separate them. 
In json, when you have multiple values, you put them in an array: "[{}, {}]" -> not "{} {}"

**Comment by Dulanic** [comment]
Ok, no biggie. I've never seen a json log use [] to wrap the whole thing. Jq and most other formatting programs can handle it, so that's why I opened this.

**Comment by matEhickey** [comment]
yup, i think that when they met an incorrect array of data, they try to split them by line return.  
Btw, it can introduce weird habit for users as json is normally very strict: no last "," on objects or arrays, no comments, etc..  
This plugin only call the strict parser (js / node) JSON.parse().  

For atom you could try to use [pretty-json](https://atom.io/packages/pretty-json) that might be a lot smarter.
